name: CI_pymembar

# TODO change to tag
#on: [push, pull_request]
on: [push]

# limit TOKEN permissions
permissions:
  contents: read

jobs:
  Build:
    environment: python-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Build C extension
        uses: pypa/cibuildwheel@v3.2.1
        with:
          output-dir: dist
        env:
          CIBW_TEST_COMMAND_LINUX: "python -m unittest discover -s {project}/tests -p 'test_*.py' -v"
          CIBW_TEST_COMMAND_MACOS: "python -m unittest discover -s {project}/tests -p 'test_*.py' -v"
          CIBW_TEST_COMMAND_WINDOWS: "python -m unittest discover -s {project}\\tests -p test_*.py -v"
