name: CI_pymembar_release

# TODO change to tag
on: [push, pull_request]

# limit GITHUB_TOKEN permissions
permissions:
  contents: read

jobs:
  Build:
    environment: python-tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: pypa/cibuildwheel@v3.2.1
      - name: Build C extension
        with:
          output-dir: dist
          
      - name: Publish to Test PyPI
        run: |
          pip install --upgrade pip
          pip install twine
          twine upload --repository testpypi dist/*.whl --verbose || { echo "::error:: ❌ Error: Upload failed. Possibly because the version already exists."; exit 1; }
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN_ENV }}
